### ISSUE TITLE
Routing does not work in local deployment

### ISSUE THREAD

**Issue by johanbrandhorst** [knative-sandbox/net-contour#357]
Hi, great project!

I've been trying to get this running in my local kubernetes environment (deployed using k3d and/or kind), but it appears there is something strange going on with `contour-external` and `contour-internal`. I don't know exactly why, but when using the latest release requests are simply not routed to the relevant `envoy` pod.

I can confirm that changing the `config-contour` to route both internal and external requests to a separate `contour` deployment works fine, e.g. using this:

```yaml
visibility: |
  ExternalIP:
    class: contour-external
    service: contour-external/envoy
  ClusterLocal:
    class: contour-internal
    service: contour-internal/envoy
```

I don't know exactly where this breaks, but in my testing I could not get any requests logged in the `contour-external` envoy pod. Everything else seemed to be working correctly, envoy seemed to be configured correctly, it just didn't seem like the requests were being sent to envoy in the first place.

**Comment by dprotaso** [comment]
Do you have a list of steps that show how you setup your local kind cluster?

I've done this in a round about way - ie. by exposing ports of the node container to the host. I'm using docker for mac

so my kind config is

```yaml
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
# This is needed in order to support projected volumes with service account tokens.
# See: https://kubernetes.slack.com/archives/CEKK1KTN2/p1600268272383600
kubeadmConfigPatches:
- |
  apiVerion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      "service-account-issuer": "kubernetes.default.svc"
      "service-account-signing-key-file": "/etc/kubernetes/pki/sa.key"
nodes:
- role: worker
  image: kindest/node:${K8S_VERSION}
- role: control-plane
  image: kindest/node:${K8S_VERSION}
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP
``` 

Our contour yaml's remove the `hostPort` on the envoy containers and I add that back

```bash
curl -L https://github.com/knative/net-contour/releases/download/${CONTOUR_VERSION}/contour.yaml | \
     sed -e $'s@# hostPort:@hostPort:@g' | \
     kubectl apply -f -

curl -L https://github.com/knative/net-contour/releases/download/${CONTOUR_VERSION}/net-contour.yaml | \
    sed -e 's@# hostPort:@hostPort:@g' | \
     kubectl apply -f -
```

Then I patch the external envoy daemon set to have the toleration.

```
 kubectl patch daemonsets/envoy -n contour-external -p '{"spec":{"template":{"spec":{"nodeSelector":{"ingress-ready":"true"},"tolerations":[{"key":"node-role.kubernetes.io/master","operator":"Equal","effect":"NoSchedule"}]}}}}'
``


Since I only have one node I think the tolerations are probably not needed

**Comment by johanbrandhorst** [comment]
I didn't do any complicated set up like this, I just followed the installation instructions. I haven't tried it since I first reported this issue.

**Comment by dprotaso** [comment]
> I didn't do any complicated set up like this, I just followed the installation instructions. I haven't tried it since I first reported this issue.

Which instructions did you follow?  With KinD (on Mac) to hit the envoy pods you'll need the config I pointed out especially

```yaml
  extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP
```

With this you should be able to curl the Docker VM
