### ISSUE TITLE
Doesn't work with common services

### ISSUE THREAD

**Issue by xpepermint** [knative-sandbox/net-contour#481]
Do I need a stand-alone Contour for serving common services or I can somehow use knative's configuration? Knative service routing works as expected but other services exposed through `Ingress` are ignored.

**Comment by dprotaso** [comment]
Do you have an example of how you're exposing the other services?

**Comment by xpepermint** [comment]
Here's a common sample deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kuard
  name: kuard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:1
        name: kuard
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard
  name: kuard
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuard
            port:
              number: 80
```

**Comment by dprotaso** [comment]
I think your ingress needs to be annotated with the contour class

It looks like contour looks at the annotation or setting spec.ingressClassName
https://github.com/projectcontour/contour/blob/00119d7860397ac5653b0633e222aa4352039c7a/internal/validation/ingress/ingress_test.go#L30-L42

**Comment by xpepermint** [comment]
The link looks promising, thanks, but unfortunately, I can't make it work.

**Comment by dprotaso** [comment]
Sorry for the delay - Knative's contour deployment actually changes the ingress class name.

You can pick from one of the following
1) `contour-external` - is accessible publicly (via your loadbalancer)
2) `contour-internal` - is accessible only within the cluster


So for external it would be 

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  ingressClassName: contour-external
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuard
            port:
              number: 80
```


If this doesn't work feel free to re-open the issue/comment again
