### ISSUE TITLE
contour ClusterRole clashes with existing contour resource when using kapp

### ISSUE THREAD

**Issue by izabelacg** [knative-sandbox/net-contour#495]
[ClusterRole contour](https://github.com/knative-sandbox/net-contour/blob/ab2f0166b5d80ae220dae1eec9572defe1884e28/config/contour/external.yaml#L1839) will clash with another Contour installation when using tools like `kapp`. Renaming it alongside with ClusterRoleBindings that reference it will prevent problems with existing non-namespaced resources.

```yaml
# line 1
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: contour-external
  labels:
    networking.knative.dev/ingress-provider: contour
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contour
subjects:
- kind: ServiceAccount
  name: contour
  namespace: contour-external
---
# line 1839
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: contour
  labels:
    networking.knative.dev/ingress-provider: contour
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - update
 ...     
```
