### ISSUE TITLE
Kubernetes labels not being added to release artifact

### ISSUE THREAD

**Issue by carlisia** [knative-sandbox/net-contour#784]
For some reason, when generating a release artifact, net-contour is including the k8s labels under `spec.template.metadata.labels`:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-contour-controller
  namespace: knative-serving
  labels:
    networking.knative.dev/ingress-provider: contour
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-contour-controller
  template:
    metadata:
      labels:
        app: net-contour-controller
        app.kubernetes.io/component: net-contour
        app.kubernetes.io/name: knative-serving
        app.kubernetes.io/version: "1.6.0"
```
Compare that with what net-kourier (corrrectly) generates:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-kourier-controller
  namespace: knative-serving
  labels:
    networking.knative.dev/ingress-provider: kourier
    app.kubernetes.io/component: net-kourier
    app.kubernetes.io/version: "1.6.0"
    app.kubernetes.io/name: knative-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-kourier-controller
  template:
    metadata:
      labels:
        app: net-kourier-controller
```

The fix is probably going to be around this line:
https://github.com/knative-sandbox/net-contour/blob/023772c9c2ed7fae5ac4e47a097a78f76b356744/hack/release.sh#L40

/bug
/good-first-issue
